# Generated by Django 4.2.4 on 2023-08-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrowed_on",
            field=models.DateTimeField(verbose_name="borrowed date"),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="due_date",
            field=models.DateTimeField(verbose_name="due date"),
        ),
    ]
