# Generated by Django 4.2.4 on 2023-08-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_system", "0002_alter_borrowing_borrowed_on_alter_borrowing_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="borrowed_on",
            field=models.DateField(verbose_name="borrowed date"),
        ),
        migrations.AlterField(
            model_name="borrowing",
            name="due_date",
            field=models.DateField(verbose_name="due date"),
        ),
    ]
