# Generated by Django 4.2.4 on 2023-08-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_system", "0004_borrowing_borrowed_status_borrowing_returned_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowing",
            name="renewed_count",
            field=models.IntegerField(default=0),
        ),
    ]
